export enum TiposAseo {
  LIMPIEZA = 'LIMPIEZA',
  DESINFECCION = 'DESINFECCION',
  ROTACION_COLCHONES = 'ROTACION_COLCHONES',
  LIMPIEZA_BANIO = 'LIMPIEZA_BANIO',
  DESINFECCION_BANIO = 'DESINFECCION_BANIO',
}