export enum EstadoHabitacion {
  LIBRE = 'LIBRE',
  OCUPADO = 'OCUPADO',
  RESERVADO = 'RESERVADO',
  EN_DESINFECCION = 'EN_DESINFECCION',
  EN_MANTENIMIENTO = 'EN_MANTENIMIENTO',
  EN_LIMPIEZA = 'EN_LIMPIEZA',
}