export enum TipoHabitacion {
  APARTAMENTO = 'APARTAMENTO',
  HAMACA = 'HAMACA',
  CAMPING = 'CAMPING',
  MÚLTIPLE = 'MÚLTIPLE',
  CASA = 'CASA',
  FINCA = 'FINCA',
  CAMA = 'CAMA',
  PLAZA = 'PLAZA',
  SENCILLA = 'SENCILLA',
  SUITE = 'SUITE',
  DOBLE = 'DOBLE',
  OTRO = 'OTRO',
}